import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import "bootstrap/dist/css/bootstrap.css";
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import About from '@/components/About'
import Events from '@/components/Events'
import Faq from '@/components/Faq';
import Timeline from '@/components/Timeline'
import Sponsors from '@/components/Sponsors'
import Glimpse from '@/components/Glimpse'
import Testimonials from '@/components/Testimonials'
import { useEffect, useRef, useState } from 'react'
import GLOBE from "vanta/dist/vanta.globe.min"
import * as THREE from "three"
import FAQ from '@/components/Faq';
// import '../node_modules/bootstrap/dist/css/bootstrap.min.css';

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [vantaEffect, setVantaEffect] = useState(0)
  const vantaRef = useRef(null)
  useEffect(() => {
    if(!vantaEffect){
      setVantaEffect(
        GLOBE({
          el: vantaRef.current,
          THREE,
          scale: 1.00,
          scaleMobile: 1.00,
          color: 0x9d2b9c,
          backgroundColor: 0x0
        })
      )
    }
    return () => {
      if (vantaEffect) vantaEffect.destroy()
    }
  }, [vantaEffect])
  return (
    <>
      <Head>
        <title>Hackfest | IIT Dhanbad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main} ref={vantaRef}>
        <div className={styles.container}>
          <h1 className={styles.ttl}>Hackfest 2k23</h1>
          <h2 className={styles.subttl}>Tagline Here</h2>
          <h2 className={styles.subttl}>7th to 9th APRIL</h2>
          <h2 className={styles.subttl}>IIT ISM Dhanbad</h2>
        </div>
      </main>
      <About/>
      <Timeline/>
      <Glimpse/>
      <Events/>
      <Testimonials/>
      <Sponsors/>
      <Faq/>
      <Footer/>

    </>
  )
}
